log/urls.py
from django.urls import path


from . import views

app_name = 'log'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.mylogin, name='my_login'),
    path('cgclogin', views.cgc_login, name='cgc_login'),
    path('postglogin', views.postg_login, name='postg_login'),
    path('formaclogin', views.formac_login, name= 'formac_login'),
    path('cgclogout', views.cgc_logout, name='cgc_logout'),
    path('<str:program_slug>/logout', views.mylogout, name='my_logout'),
    path('cgc/member/<int:member_id>/pic', views.cgc_member_picture, name='cgc_member_picture'),



]

programas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('accounts/password_reset/done/', auth_views.PasswordResetDoneView().as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('admin/', admin.site.urls),
    path('', include('log.urls', namespace='log')),
    path('cgc/', include('programs.cgcurls', namespace='cgc')),
    path('postg/', include('programs.postgurls', namespace='postg')),
    path('formac/', include('programs.formacurls', namespace='formac')),
    path('<str:program_slug>/', include('programs.urls', namespace='programs')),
    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

programs/urls.py
from django.urls import path


from . import views
from . import cgc_views as cgc_views
from .formac_views import ajx_students_by_center, program_statistics


app_name = 'programs'

urlpatterns = [
    path('', views.index, name='index'),
    path('comments/<int:thesis_id>/new', views.new_phd_thesis_comment, name='new_phd_thesis_comment'),
    path('edit', views.edit_program, name='edit_program'),
    path('home/', views.home, name='home'),
    path('background/<int:background_id>', views.program_background, name='program_background'),
    #Path de estudiantes de doctorados, excepto la lista
    path('students/create', views.create_student, name='create_student'),
    path('students/list/<str:scope>', views.students_list, name='students_list'),
    path('students/csv/export/<str:scope>', views.export_csv_students, name='export_csv_students'),
    path('students/<int:student_id>/edit', views.edit_student, name='edit_student'),
    path('students/<int:student_id>/thesis/new', views.ajx_new_phd_thesis, name='ajx_new_phd_thesis'),
    path('students/<int:student_id>/thesis/remove', views.ajx_rm_phd_thesis, name='ajx_rm_phd_thesis'),
    path('students/<int:student_id>/profile', views.view_student_profile, name='view_student_profile'),
    path('students/<int:student_id>/autoedit/profile', views.autoedit_student_profile, name='autoedit_student_profile'),
    path('students/<int:student_id>/picture', views.program_student_picture, name='program_student_picture'),
    path('students/<int:student_id>/evaluate', views.evaluate_student, name='evaluate_student'),
    path('students/<int:student_id>/evaluations', views.student_evals, name='student_evals'),
    path('students/<int:student_id>/print/evals', views.print_student_evals, name='print_student_evals'),
    path('students/<int:student_id>/plan/create', views.create_formation_plan, name='create_formation_plan'),
    path('students/<int:student_id>/plan/edit', views.edit_formation_plan, name='edit_formation_plan'),
    path('students/<int:student_id>/plan/view', views.view_formation_plan, name='view_formation_plan'),
    path('students/<int:student_id>/plan/print', views.print_student_plan, name='print_student_plan'),
    path('students/<int:student_id>/file/<int:doc_id>/view', views.student_filedoc_view, name='student_filedoc_view'),

    #Paths de estudiantes de maestria
    path('', views.msc_index, name='msc_index'),
    path('msc/<int:edition_id>/students/create', views.create_msc_student, name='create_msc_student'),
    path('msc/<int:edition_id>/students/<int:student_id>/edit', views.edit_msc_student, name='edit_msc_student'),
    path('msc/edition/<int:edition_id>/students/<str:scope>/list', views.msc_edition_students_list, name='msc_edition_students_list'),
    path('msc/students/<str:scope>/list', views.msc_all_students_list, name='msc_all_students_list'),

    #Paths de estudiantes de cursos
    path('', views.curs_index, name='curs_index'),
    path('curs/<int:edition_id>/students/create', views.create_curs_student, name='create_curs_student'),
    path('curs/<int:edition_id>/students/<int:student_id>/edit', views.edit_curs_student, name='edit_curs_student'),
    path('curs/edition/<int:edition_id>/students/<str:scope>/list', views.curs_edition_students_list, name='curs_edition_students_list'),
    path('curs/students/<str:scope>/list', views.curs_all_students_list, name='curs_all_students_list'),

    #Paths de estudiantes de colegio
    path('', views.coleg_index, name='coleg_index'),
    path('coleg/<int:edition_id>/students/create', views.create_coleg_student, name='create_coleg_student'),
    path('coleg/<int:edition_id>/students/<int:student_id>/edit', views.edit_coleg_student, name='edit_coleg_student'),
    path('coleg/edition/<int:edition_id>/students/<str:scope>/list', views.coleg_edition_students_list, name='coleg_edition_students_list'),
    path('coleg/students/<str:scope>/list', views.coleg_all_students_list, name='coleg_all_students_list'),
   
    path('', views.dip_index, name='dip_index'),
    path('dip/<int:edition_id>/students/create', views.create_dip_student, name='create_dip_student'),
    path('dip/<int:edition_id>/students/<int:student_id>/edit', views.edit_dip_student, name='edit_dip_student'),
    path('dip/edition/<int:edition_id>/students/<str:scope>/list', views.dip_edition_students_list, name='dip_edition_students_list'),
    path('dip/students/<str:scope>/list', views.dip_all_students_list, name='dip_all_students_list'),

    path('professors/create', views.create_professor, name='create_professor'),
    path('professors/<int:member_id>/edit', views.edit_member, name='edit_member'),
    path('professors/<int:member_id>/picture', views.program_member_picture, name='program_member_picture'),
    path('professors/<str:scope>/list', views.members_list, name='members_list'),
    path('professors/<int:member_id>/view/profile', views.view_program_member_profile, name='view_program_member_profile'),
    path('professors/<int:member_id>/autoedit/profile', views.autoedit_member_profile, name='autoedit_member_profile'),

    path('lines/create', views.create_line, name='create_line'),
    path('lines/list', views.program_lines, name='program_lines'),
    path('lines/<int:line_id>/students', views.students_by_line, name='students_by_line'),
    path('lines/<int:line_id>/edit', views.edit_line, name='edit_line'),

    path('projects/create', views.create_project, name='create_project'),
    path('projects/<int:project_id>/edit', views.edit_project, name='edit_project'),
    path('projects/list', views.projects_list, name='projects_list'),

    path('editions/create',views.create_program_edition, name='create_program_edition'),
    path('editions/list',views.editions_list, name='editions_list'),
    path('editions/<int:edition_id>/edit',views.edit_program_edition, name='edit_program_edition'),
    path('editions/<int:edition_id>/course/create',views.create_edition_course, name='create_edition_course'),
    path('editions/<int:edition_id>/courses',views.edition_courses, name='edition_courses'),
    path('editions/<int:edition_id>/courses/print',views.print_edition_courses_registers, name='print_edition_courses_registers'),

    path('courses/create', views.create_program_course, name='create_program_course'),
    path('courses/list', views.program_courses, name='program_courses'),
    path('courses/<int:course_id>/edit', views.edit_program_course, name='edit_program_course'),
    path('courses/<int:course_id>/print/register', views.print_course_register, name='print_course_register'),


    path('ajx/document/file/update', views.ajx_update_filedoc, name='ajx_update_filedoc'),
    path('ajx/document/file/upgrade', views.ajx_upgrade_filedoc, name='ajx_upgrade_filedoc'),
    path('ajx/document/file/delete', views.ajx_delete_filedoc, name='ajx_delete_filedoc'),

    path('ajx/user/exists', views.ajx_usr_exists, name='ajx_usr_exists'),
    path('ajx/member/exists', views.ajx_program_member_tuthor, name='ajx_program_member_tuthor'),
    path('ajx/student/delete', views.ajx_delete_student, name='ajx_delete_student'),
    path('ajx/student/autorequest', views.ajx_auto_request, name='ajx_auto_request'),
    path('ajx/member/delete', views.ajx_delete_member, name='ajx_delete_member'),
    path('ajx/tuthor/delete', views.ajx_delete_tuthor, name='ajx_delete_tuthor'),

    path('ajx/student/<int:student_id>/tuthor/create', views.ajx_create_tuthor, name='ajx_create_tuthor'),
    path('ajx/student/<int:student_id>/plan/activity/add', views.ajx_create_activity, name='ajx_create_activity'),
    path('ajx/student/<int:student_id>/plan/activity/edit', views.ajx_edit_activity, name='ajx_edit_activity'),
    path('ajx/student/<int:student_id>/plan/activity/delete', views.ajx_delete_activity, name='ajx_delete_activity'),
    path('ajx/student/exists', views.ajx_student_exists, name='ajx_student_exists'),

    path('ajx/line/delete', views.ajx_delete_line, name='ajx_delete_line'),
    path('ajx/line/projects', views.ajx_line_projects, name='ajx_line_projects'),
    path('ajx/edition/delete', views.ajx_delete_program_edition, name='ajx_delete_program_edition'),
    path('ajx/project/delete', views.ajx_delete_project, name='ajx_delete_project'),
    

    path('ajx/statistics/thisyear/requests', views.ajx_this_year_requests, name='ajx_this_year_requests'),
    path('ajx/statistics/byyear/requests', views.ajx_by_year_requests, name='ajx_by_year_requests'),
    path('ajx/statistics/lastyear/requests', views.ajx_last_years_requests, name='ajx_last_years_requests'),
    path('ajx/statistics/students/status', views.ajx_students_by_state, name='ajx_students_by_state'),
    path('ajx/statistics/students/gender', views.ajx_students_by_sex, name='ajx_students_by_sex'),
    path('ajx/statistics/students/<str:scope>/line', views.ajx_students_by_line, name='ajx_students_by_line'),
    path('ajx/statistics/students/line/donut', views.ajx_students_by_line_donut, name='ajx_students_by_line_donut'),
    path('ajx/statistics/students/category', views.ajx_students_by_category, name='ajx_students_by_category'),
    path('ajx/statistics/students/country', views.ajx_students_by_country, name='ajx_students_by_country'),
    path('ajx/statistics/students/age', views.ajx_students_by_age, name='ajx_students_by_age'),
    path('ajx/statistics/students/editions', views.ajx_students_by_edition, name='ajx_students_by_edition'),
    path('ajx/statistics/students/graduated/editions', views.ajx_graduated_by_edition, name='ajx_graduated_by_edition'),
    path('ajx/statistics/members/degree', views.ajx_members_by_grade, name='ajx_members_by_grade'),
    path('ajx/statistics/members/age', views.ajx_members_by_age, name='ajx_members_by_age'),
    path('ajx/statistics/next/defenses', views.ajx_next_years_defenses, name='ajx_next_years_defenses'),
    
   
    path('ajx/messages/members/personal', views.ajx_member_personal_msg, name='ajx_member_personal_msg'),

programs/forms.py
from django import forms

from programs.models import PhdAnnouncement, PhdStudentThesis, PhdThesisComment


class FileUploadForm(forms.Form):
    file_source = forms.FileField()



class AnnouncementForm(forms.ModelForm):
    class Meta:
        model = PhdAnnouncement
        fields = '__all__'

class PhdStudentThesisForm(forms.ModelForm):

    class Meta:
        model = PhdStudentThesis
        fields = '__all__'


class PhdThesisCommentForm(forms.ModelForm):

    class Meta:
        model = PhdThesisComment
        fields = '__all__'

programs/templates/programs/formac/create_new.html
{% extends 'programs/formac/formac_base.html' %}
{% load static %}
{% load extra_tags %}

{% block extra_css %}

{% endblock %}

{% block formac_content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-9">
                    <h1>Agregar noticia</h1>
                </div>
                <div class="col-sm-3">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'formac:formac_home'  %}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Nueva noticia</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Noticia</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="post" enctype="multipart/form-data" action="{% url 'formac:create_new'  %}">
                            {% csrf_token %}
                            <div class="card-body">
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label for="inp_name">Título:</label>
                                        <input class="form-control" id="inp_title" name="new_title" placeholder="Título de la noticia" maxlength="100" required></input>
                                    </div>

                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <textarea class="form-control textarea col-md-12" id="txt_new_body"
                                                  name="new_body" placeholder="Cuerpo de la noticia" rows="8" maxlength="4000" required ></textarea>
                                    </div>

                                </div>



                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Guardar</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->



                    <!-- /.card -->

                    <!-- Input addon -->
                    <!-- /.card -->
                    <!-- Horizontal Form -->
                    <!-- /.card -->

                </div>
                <!--/.col (left) -->
                <!-- right column -->
                <!--/.col (right) -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}

<!-- jQuery -->
{% block extra_scripts %}
    <!-- AdminLTE App -->

    <script>
        $(document).ready(function () {
            $('#txt_new_body').summernote({
                lang: 'es-Es',
                placeholder: 'Escriba el cuerpo de la noticia aquí.',
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                dialogsInBody: true,
                dialogsFade: true,
                height: 200,
                toolbar: [
                    // [groupName, [list of button]]
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['font', ['strikethrough', 'superscript', 'subscript']],
                    {#['fontname', ['fontname']],#}
                    {#['fontsize', ['fontsize']],#}
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture', 'video']],
                    ['view', ['fullscreen', 'codeview', 'help']],
                ],

            });
        });
    </script>
{% endblock %}
</body>
</html>

programs/templates/programs/formac/edit_new.html
{% extends 'programs/formac/formac_base.html' %}
{% load static %}
{% load extra_tags %}

{% block extra_css %}

{% endblock %}

{% block formac_content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-9">
                    <h1>Editar noticia</h1>
                </div>
                <div class="col-sm-3">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'formac:formac_home' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Editar noticia</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Noticia</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="post" enctype="multipart/form-data" action="{% url 'formac:edit_new' new.id %}">
                            {% csrf_token %}
                            <div class="card-body">
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label for="inp_name">Título:</label>
                                        <input class="form-control" id="inp_title" name="new_title" placeholder="Título de la noticia" value="{{ new.title }}" maxlength="100" required></input>
                                    </div>

                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <textarea class="form-control textarea col-md-12" id="txt_new_body"
                                                  name="new_body" placeholder="Cuerpo de la noticia" rows="8" maxlength="4000" required >{{ new.body }}</textarea>
                                    </div>

                                </div>


                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Guardar</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->



                    <!-- /.card -->

                    <!-- Input addon -->
                    <!-- /.card -->
                    <!-- Horizontal Form -->
                    <!-- /.card -->

                </div>
                <!--/.col (left) -->
                <!-- right column -->
                <!--/.col (right) -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}

<!-- jQuery -->
{% block extra_scripts %}
    <!-- AdminLTE App -->

    <script>
        $(document).ready(function () {
            $('#txt_new_body').summernote({
                lang: 'es-Es',
                placeholder: 'Escriba el cuerpo de la noticia aquí.',
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                dialogsInBody: true,
                dialogsFade: true,
                height: 300,
                toolbar: [
                    // [groupName, [list of button]]
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['font', ['strikethrough', 'superscript', 'subscript']],
                    {#['fontname', ['fontname']],#}
                    {#['fontsize', ['fontsize']],#}
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture', 'video']],
                    ['view', ['fullscreen', 'codeview', 'help']],
                ],

            });
        });
    </script>
{% endblock %}
</body>
</html>

programs/templates/programs/formac/formac_members_list.html
{% extends 'programs/formac/formac_base.html' %}
{% load static %}
{% load extra_tags %}


{% block extra_css %}
    <!-- Ionicons -->
    {# <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %}"> #}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'programs/plugins/datatables-bs4/css/dataTables.bootstrap4.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'programs/dist/css/adminlte.min.css' %}">
{% endblock %}

{% block formac_content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-9">
                    <h1>Miembros de la  Dirección de Formación</h1>
                </div>
                <div class="col-sm-3">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'formac:formac_home'  %}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Miembros</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">

                <!-- /.card -->

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Miembros </h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            {% user_is_formac_ps user as user_is_formac_cs %}

                            <tr>
                                <th>Nombre y apellidos</th>
                                <th>Cargo</th>
                                {% if member.charge == 'Director' %}
                                <th></th>
                                {% endif %}


                            </tr>
                            </thead>
                            <tbody>
                            {% for pmember in members %}

                                <tr id="tr_pmember_{{pmember.id }}">
                                    <td>{{ pmember.user.last_name|upper }}, {{pmember.user.first_name }}</td>
                                    <td>{{ pmember.charge }}</td>
                                    {% if member.charge == 'Director' %}
                                        <td class="text-center">
                                            <div class="btn-group">

                                                <a class="btn btn-sm btn-warning" href="{% url 'formac:edit_formac_member' pmember.id %}" title="Editar acta"><i class="fa fa-edit"></i> </a>
                                                <button class="btn btn-sm btn-danger {% if pmember.user == user %}disabled{% endif %}" type="button" data-toggle="modal" data-target="#modal_rm_member_{{ pmember.id }}" title="Eliminar miembro"><i class="fa fa-eraser"></i> </button>


                                            </div>
                                        </td>
                                    {% endif %}
                                </tr>

                                <div class="modal fade" id="modal_rm_member_{{ pmember.id }}">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">Eliminar miembro</h4>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="row">
                                                    <div class="col-md-2">
                                                        <span class="text-danger"><i class="fa fa-exclamation-triangle fa-4x"></i></span>

                                                    </div>
                                                    <div class="col-md-10">
                                                        <p class="text-center">¿Seguro que desea eliminar a {{ pmember }}?<br>Esto no se puede deshacer&hellip;</p>
                                                    </div>
                                                </div>

                                            </div>
                                            <div class="modal-footer justify-content-between">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                                <button type="button" class="btn btn-danger " data-dismiss="modal" data="{{  pmember.id }}" id="btn_rm_member_{{ pmember.id }}">Eliminar</button>
                                            </div>
                                        </div>
                                        <!-- /.modal-content -->
                                    </div>
                                    <!-- /.modal-dialog -->
                                </div>

                            {% endfor %}

                            </tbody>
                            <tfoot>
                            {#                            <tr>#}
                            {#                                <th>Nombre y apellidos</th>#}
                            {#                                <th>Fecha solicitud</th>#}
                            {#                                <th>Estado</th>#}
                            {#                                <th class="text-center">Requisitos</th>#}
                            {#                                <th></th>#}
                            {#                            </tr>#}
                            </tfoot>
                            {% csrf_token %}
                        </table>

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        {% csrf_token %}
        <!-- /.row -->
    </section>
    <!-- /.content -->
    </div>
{% endblock %}
{% block extra_scripts %}
    <!-- jQuery -->
    <!-- Bootstrap 4 -->
    <!-- DataTables -->
    <script src="{% static 'programs/plugins/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'programs/plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>



    <!-- AdminLTE App -->
    {#    <script src="{% static 'programs/dist/js/adminlte.min.js' %}"></script>#}
    <!-- AdminLTE for demo purposes -->
    {#    <script src="{% static 'programs/dist/js/demo.js' %}"></script>#}
    <!-- page script -->
    <script>

        $(document).ready(function () {
            var myTable = $("#example1").DataTable({
                language: {
                    url: '{% static "programs/plugins/datatables/Spanish.json" %}'
                }});
            const Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 7000
            });

            {% for pmember in members %}
                $('#btn_rm_member_{{ pmember.id }}').click(function () {

                    var member_id={{ pmember.id }};
                    var url = "{% url 'formac:ajx_delete_member' %}";

                    $('#modal_rm_member_{{ pmember.id }}').modal('hide');

                    $.ajax({
                        url : url,
                        type : "POST", // http method
                        data : {'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val(),
                            'member_id':member_id,
                        }, // data sent with the post request

                        // handle a successful response
                        success : function(json) {

                            if (json[0].deleted == 1) {
                                var row = myTable.row( $('#tr_pmember_{{ pmember.id }}') );
                                row.remove().draw();

                                Toast.fire({
                                    type: 'success',
                                    title: 'Miembro eliminado exitósamente'
                                })

                            } else if(json[0].deleted == 0){
                                Toast.fire({
                                    type: 'error',
                                    title: 'No se ha podido eliminar al trabajador seleccionado.'
                                })

                            }
                            else if(json[0].deleted == 2){
                                Toast.fire({
                                    type: 'error',
                                    title: 'Usted no tiene privilegios para eliminar miembros de la Dir. de Formación.'
                                })

                            }
                            console.log(json); // log the returned json to the console
                            console.log("success"); // another sanity check




                            $('#div_by_workshop').removeClass('hidden')

                        },

                        // handle a non-successful response
                        error : function(xhr,errmsg,err) {
                            Toast.fire({
                                type: 'error',
                                title: 'Uff, ha ocurrido algo desconocido.'
                            })
                        }
                    });

                });
            {% endfor %}


        })
    </script>
{% endblock %}
</body>
</html>