log/urls.py
from django.urls import path


from . import views

app_name = 'log'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.mylogin, name='my_login'),
    path('cgclogin', views.cgc_login, name='cgc_login'),
    path('postglogin', views.postg_login, name='postg_login'),
    path('formaclogin', views.formac_login, name= 'formac_login'),
    path('cgclogout', views.cgc_logout, name='cgc_logout'),
    path('<str:program_slug>/logout', views.mylogout, name='my_logout'),
    path('cgc/member/<int:member_id>/pic', views.cgc_member_picture, name='cgc_member_picture'),



]

programs/urls.py
from django.urls import path


from . import views
from . import cgc_views as cgc_views
from .formac_views import ajx_students_by_center, program_statistics


app_name = 'programs'

urlpatterns = [
    path('', views.index, name='index'),
    path('comments/<int:thesis_id>/new', views.new_phd_thesis_comment, name='new_phd_thesis_comment'),
    path('edit', views.edit_program, name='edit_program'),
    path('home/', views.home, name='home'),
    path('background/<int:background_id>', views.program_background, name='program_background'),
    #Path de estudiantes de doctorados, excepto la lista
    path('students/create', views.create_student, name='create_student'),
    path('students/list/<str:scope>', views.students_list, name='students_list'),
    path('students/csv/export/<str:scope>', views.export_csv_students, name='export_csv_students'),
    path('students/<int:student_id>/edit', views.edit_student, name='edit_student'),
    path('students/<int:student_id>/thesis/new', views.ajx_new_phd_thesis, name='ajx_new_phd_thesis'),
    path('students/<int:student_id>/thesis/remove', views.ajx_rm_phd_thesis, name='ajx_rm_phd_thesis'),
    path('students/<int:student_id>/profile', views.view_student_profile, name='view_student_profile'),
    path('students/<int:student_id>/autoedit/profile', views.autoedit_student_profile, name='autoedit_student_profile'),
    path('students/<int:student_id>/picture', views.program_student_picture, name='program_student_picture'),
    path('students/<int:student_id>/evaluate', views.evaluate_student, name='evaluate_student'),
    path('students/<int:student_id>/evaluations', views.student_evals, name='student_evals'),
    path('students/<int:student_id>/print/evals', views.print_student_evals, name='print_student_evals'),
    path('students/<int:student_id>/plan/create', views.create_formation_plan, name='create_formation_plan'),
    path('students/<int:student_id>/plan/edit', views.edit_formation_plan, name='edit_formation_plan'),
    path('students/<int:student_id>/plan/view', views.view_formation_plan, name='view_formation_plan'),
    path('students/<int:student_id>/plan/print', views.print_student_plan, name='print_student_plan'),
    path('students/<int:student_id>/file/<int:doc_id>/view', views.student_filedoc_view, name='student_filedoc_view'),

    #Paths de estudiantes de maestria
    path('', views.msc_index, name='msc_index'),
    path('msc/<int:edition_id>/students/create', views.create_msc_student, name='create_msc_student'),
    path('msc/<int:edition_id>/students/<int:student_id>/edit', views.edit_msc_student, name='edit_msc_student'),
    path('msc/edition/<int:edition_id>/students/<str:scope>/list', views.msc_edition_students_list, name='msc_edition_students_list'),
    path('msc/students/<str:scope>/list', views.msc_all_students_list, name='msc_all_students_list'),

    #Paths de estudiantes de cursos
    path('', views.curs_index, name='curs_index'),
    path('curs/<int:edition_id>/students/create', views.create_curs_student, name='create_curs_student'),
    path('curs/<int:edition_id>/students/<int:student_id>/edit', views.edit_curs_student, name='edit_curs_student'),
    path('curs/edition/<int:edition_id>/students/<str:scope>/list', views.curs_edition_students_list, name='curs_edition_students_list'),
    path('curs/students/<str:scope>/list', views.curs_all_students_list, name='curs_all_students_list'),

    #Paths de estudiantes de colegio
    path('', views.coleg_index, name='coleg_index'),
    path('coleg/<int:edition_id>/students/create', views.create_coleg_student, name='create_coleg_student'),
    path('coleg/<int:edition_id>/students/<int:student_id>/edit', views.edit_coleg_student, name='edit_coleg_student'),
    path('coleg/edition/<int:edition_id>/students/<str:scope>/list', views.coleg_edition_students_list, name='coleg_edition_students_list'),
    path('coleg/students/<str:scope>/list', views.coleg_all_students_list, name='coleg_all_students_list'),
   
    path('', views.dip_index, name='dip_index'),
    path('dip/<int:edition_id>/students/create', views.create_dip_student, name='create_dip_student'),
    path('dip/<int:edition_id>/students/<int:student_id>/edit', views.edit_dip_student, name='edit_dip_student'),
    path('dip/edition/<int:edition_id>/students/<str:scope>/list', views.dip_edition_students_list, name='dip_edition_students_list'),
    path('dip/students/<str:scope>/list', views.dip_all_students_list, name='dip_all_students_list'),

    path('professors/create', views.create_professor, name='create_professor'),
    path('professors/<int:member_id>/edit', views.edit_member, name='edit_member'),
    path('professors/<int:member_id>/picture', views.program_member_picture, name='program_member_picture'),
    path('professors/<str:scope>/list', views.members_list, name='members_list'),
    path('professors/<int:member_id>/view/profile', views.view_program_member_profile, name='view_program_member_profile'),
    path('professors/<int:member_id>/autoedit/profile', views.autoedit_member_profile, name='autoedit_member_profile'),

    path('lines/create', views.create_line, name='create_line'),
    path('lines/list', views.program_lines, name='program_lines'),
    path('lines/<int:line_id>/students', views.students_by_line, name='students_by_line'),
    path('lines/<int:line_id>/edit', views.edit_line, name='edit_line'),

    path('projects/create', views.create_project, name='create_project'),
    path('projects/<int:project_id>/edit', views.edit_project, name='edit_project'),
    path('projects/list', views.projects_list, name='projects_list'),

    path('editions/create',views.create_program_edition, name='create_program_edition'),
    path('editions/list',views.editions_list, name='editions_list'),
    path('editions/<int:edition_id>/edit',views.edit_program_edition, name='edit_program_edition'),
    path('editions/<int:edition_id>/course/create',views.create_edition_course, name='create_edition_course'),
    path('editions/<int:edition_id>/courses',views.edition_courses, name='edition_courses'),
    path('editions/<int:edition_id>/courses/print',views.print_edition_courses_registers, name='print_edition_courses_registers'),

    path('courses/create', views.create_program_course, name='create_program_course'),
    path('courses/list', views.program_courses, name='program_courses'),
    path('courses/<int:course_id>/edit', views.edit_program_course, name='edit_program_course'),
    path('courses/<int:course_id>/print/register', views.print_course_register, name='print_course_register'),


    path('ajx/document/file/update', views.ajx_update_filedoc, name='ajx_update_filedoc'),
    path('ajx/document/file/upgrade', views.ajx_upgrade_filedoc, name='ajx_upgrade_filedoc'),
    path('ajx/document/file/delete', views.ajx_delete_filedoc, name='ajx_delete_filedoc'),

    path('ajx/user/exists', views.ajx_usr_exists, name='ajx_usr_exists'),
    path('ajx/member/exists', views.ajx_program_member_tuthor, name='ajx_program_member_tuthor'),
    path('ajx/student/delete', views.ajx_delete_student, name='ajx_delete_student'),
    path('ajx/student/autorequest', views.ajx_auto_request, name='ajx_auto_request'),
    path('ajx/member/delete', views.ajx_delete_member, name='ajx_delete_member'),
    path('ajx/tuthor/delete', views.ajx_delete_tuthor, name='ajx_delete_tuthor'),

    path('ajx/student/<int:student_id>/tuthor/create', views.ajx_create_tuthor, name='ajx_create_tuthor'),
    path('ajx/student/<int:student_id>/plan/activity/add', views.ajx_create_activity, name='ajx_create_activity'),
    path('ajx/student/<int:student_id>/plan/activity/edit', views.ajx_edit_activity, name='ajx_edit_activity'),
    path('ajx/student/<int:student_id>/plan/activity/delete', views.ajx_delete_activity, name='ajx_delete_activity'),
    path('ajx/student/exists', views.ajx_student_exists, name='ajx_student_exists'),

    path('ajx/line/delete', views.ajx_delete_line, name='ajx_delete_line'),
    path('ajx/line/projects', views.ajx_line_projects, name='ajx_line_projects'),
    path('ajx/edition/delete', views.ajx_delete_program_edition, name='ajx_delete_program_edition'),
    path('ajx/project/delete', views.ajx_delete_project, name='ajx_delete_project'),
    

    path('ajx/statistics/thisyear/requests', views.ajx_this_year_requests, name='ajx_this_year_requests'),
    path('ajx/statistics/byyear/requests', views.ajx_by_year_requests, name='ajx_by_year_requests'),
    path('ajx/statistics/lastyear/requests', views.ajx_last_years_requests, name='ajx_last_years_requests'),
    path('ajx/statistics/students/status', views.ajx_students_by_state, name='ajx_students_by_state'),
    path('ajx/statistics/students/gender', views.ajx_students_by_sex, name='ajx_students_by_sex'),
    path('ajx/statistics/students/<str:scope>/line', views.ajx_students_by_line, name='ajx_students_by_line'),
    path('ajx/statistics/students/line/donut', views.ajx_students_by_line_donut, name='ajx_students_by_line_donut'),
    path('ajx/statistics/students/category', views.ajx_students_by_category, name='ajx_students_by_category'),
    path('ajx/statistics/students/country', views.ajx_students_by_country, name='ajx_students_by_country'),
    path('ajx/statistics/students/age', views.ajx_students_by_age, name='ajx_students_by_age'),
    path('ajx/statistics/students/editions', views.ajx_students_by_edition, name='ajx_students_by_edition'),
    path('ajx/statistics/students/graduated/editions', views.ajx_graduated_by_edition, name='ajx_graduated_by_edition'),
    path('ajx/statistics/members/degree', views.ajx_members_by_grade, name='ajx_members_by_grade'),
    path('ajx/statistics/members/age', views.ajx_members_by_age, name='ajx_members_by_age'),
    path('ajx/statistics/next/defenses', views.ajx_next_years_defenses, name='ajx_next_years_defenses'),
    
   
    path('ajx/messages/members/personal', views.ajx_member_personal_msg, name='ajx_member_personal_msg'),

log/models.py
from django.db import models

# Create your models here.

log/templates/log/login_error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Programas Académicos, UH</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static '/log/img/favicon.png' %}" rel="icon">
    <link href="{% static '/log/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static '/log/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/log/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/log/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static '/log/vendor/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
    <link href="{% static '/log/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static '/log/vendor/venobox/venobox.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static '/log/css/style.css' %}" rel="stylesheet">

    <!-- =======================================================
    * Template Name: NewBiz - v2.0.0
    * Template URL: https://bootstrapmade.com/newbiz-bootstrap-business-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container">

        <div class="logo float-left">
            <!-- Uncomment below if you prefer to use an text logo -->
            <h1 class="text-light"><a href="#header"><span>Programas</span></a></h1>
            {#        <a href="#intro" class="scrollto">Programas</a>#}
        </div>

        <nav class="main-nav float-right d-none d-lg-block">
            <ul>
                <li class="active"><a href="{% url 'programs:index' program.slug %}#contact">Inicio</a></li>


            </ul>
        </nav><!-- .main-nav -->

    </div>
</header><!-- #header -->

<!-- ======= Intro Section ======= -->
<section id="intro" class="clearfix">
    <div class="container">

        <div class="intro-img">
            <img src="{% static '/log/img/intro-img.svg' %} " alt="" class="img-fluid">
        </div>

        <div class="intro-info">
            <h2><span>Error!!!</span></h2>
            <div>
                <h3 class="text-warning"> {{ error_message }}:{{ program.short_name }}</h3>
            </div>
        </div>

    </div>
</section><!-- End Intro Section -->

<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="footer-info">
                    <h3>Programas</h3>
                    <p>Sistema para la gestión de programas académicos en la UH.</p>
                </div>





            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong>LATED, UNAH</strong>. Todos los derechos reservados
        </div>
        <div class="credits">
            <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=NewBiz
          -->
            <a href="https://bootstrapmade.com/"></a>
        </div>

    </div>

</footer><!-- End Footer -->

<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

<!-- Vendor JS Files -->
<script src="{% static '/log/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static '/log/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static '/log/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
<script src="{% static '/log/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static '/log/vendor/counterup/counterup.min.js' %}"></script>
<script src="{% static '/log/vendor/mobile-nav/mobile-nav.js' %}"></script>
<script src="{% static '/log/vendor/wow/wow.min.js' %}"></script>
<script src="{% static '/log/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static '/log/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static '/log/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
<script src="{% static '/log/vendor/venobox/venobox.min.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static '/log/js/main.js' %}"></script>

</body>

</html>